### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by disassembler** [ThomArmax/HUPnP#7]
Can you tag a release? I'm switching from the version you forked from to this because it was easier to get to build in latest NixOS and I'm trying to get this in 17.09, but it would be nice if a release could be tagged I can reference instead of pointing at HEAD.

**Comment by ThomArmax** [comment]
Hi Samuel. Yes le course I Will do it Asap.

Le 2 sept. 2017 05:37, "Samuel Leathers" <notifications@github.com> a
écrit :

Can you tag a release? I'm switching from the version you forked from to
this because it was easier to get to build in latest NixOS and I'm trying
to get this in 17.09, but it would be nice if a release could be tagged I
can reference instead of pointing at HEAD.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ThomArmax/HUPnP/issues/7>, or mute the thread

**Comment by ThomArmax** [comment]
I thought to change the core's version to 2.0.1, and update the change log with the modifications I did since I forked the repo. Is it fine for you ?

**Comment by disassembler** [comment]
Yes, that would be great!

Thank you so much.

**Comment by ThomArmax** [comment]
I have created the requested tag (https://github.com/ThomArmax/HUPnP/releases/tag/2.1.0)

Best regards
